### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by MWagnerISP** [fernandreu/office-ribbonx-editor#176]
While trying to remove a duplicated icon from the object list

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at OfficeRibbonXEditor.ViewModels.Documents.OfficePartViewModel.RemoveIcon(String id)
   at OfficeRibbonXEditor.ViewModels.Windows.MainWindowViewModel.ExecuteRemoveItemCommand()
```

**To Reproduce**
Please describe the steps that lead to the unhandled exception here, including example files if relevant.

**Screenshots**
If applicable, add screenshots to help explain how the unhandled exception occurred.

**Additional context**

- Version: 1.6.0.493
- Runtime: .NET Framework 4.8.4300.0
- Operating System: Microsoft Windows 10.0.18363

**Comment by fernandreu** [comment]
I think this should have been fixed as part of recent updates, perhaps in v1.9 already
