### ISSUE TITLE
ArgumentException: The path is not of a legal form.

### ISSUE THREAD

**Issue by mariodinoia** [fernandreu/office-ribbonx-editor#208]
**Describe the bug**

```
System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at OfficeRibbonXEditor.ViewModels.Windows.MainWindowViewModel.<>c__DisplayClass89_0.<FinishOpeningFile>b__0(OfficeDocumentViewModel x) in C:\Users\FernA\agent\_work\1\s\src\OfficeRibbonXEditor\ViewModels\Windows\MainWindowViewModel.cs:line 689
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at OfficeRibbonXEditor.ViewModels.Windows.MainWindowViewModel.FinishOpeningFile(String fileName) in C:\Users\FernA\agent\_work\1\s\src\OfficeRibbonXEditor\ViewModels\Windows\MainWindowViewModel.cs:line 689
```

**To Reproduce**
Please describe the steps that lead to the unhandled exception here, including example files if relevant.

**Screenshots**
If applicable, add screenshots to help explain how the unhandled exception occurred.

**Additional context**

- Version: 1.9.0.1056
- Runtime: .NET Framework 4.8.4470.0
- Operating System: Microsoft Windows 10.0.19044

**Comment by mariodinoia** [comment]
![Capture](https://user-images.githubusercontent.com/7964485/168003295-64f6b4ac-b00d-4c49-bf0a-6a70432e1c23.JPG)
I loaded 4 Files to copy the ribbon between them and the 4th file came up with this errror when saving
